import { SimulationState, Agent, Company, Building, Job, Personality, SkillType, TabooIndex, BlockedAction } from '@/types';
import { TABOO_ACTIONS } from '@/types/governance';

// 10 unique agents
const createAgents = (): Agent[] => [
  {
    id: 'luna-01',
    name: 'Echo',
    personality: 'ambitious',
    age: 0,
    mood: 75,
    energy: 80,
    wealth: 100,
    savings: 100,
    skills: [
      { type: 'programming', level: 65, experiencePoints: 0, lastUpdated: 0 },
      { type: 'management', level: 40, experiencePoints: 0, lastUpdated: 0 },
    ],
    jobId: null,
    companyId: null,
    employeesManaged: [],
    relationships: {},
    memory: [],
    goals: [{
      id: 'goal-echo-1',
      type: 'career',
      description: 'Become a tech company founder',
      progress: 30,
      priority: 95,
      completed: false,
    }],
    position: { x: 100, y: 100 },
    createdAt: 0,
    reputation: 70,
    isAlive: true,
  },
  {
    id: 'luna-02',
    name: 'Nova',
    personality: 'creative',
    age: 0,
    mood: 85,
    energy: 90,
    wealth: 80,
    savings: 80,
    skills: [
      { type: 'design', level: 80, experiencePoints: 0, lastUpdated: 0 },
      { type: 'marketing', level: 60, experiencePoints: 0, lastUpdated: 0 },
    ],
    jobId: null,
    companyId: null,
    employeesManaged: [],
    relationships: {},
    memory: [],
    goals: [{
      id: 'goal-nova-1',
      type: 'creative',
      description: 'Build a design studio',
      progress: 20,
      priority: 90,
      completed: false,
    }],
    position: { x: 200, y: 150 },
    createdAt: 0,
    reputation: 65,
    isAlive: true,
  },
  {
    id: 'luna-03',
    name: 'Cipher',
    personality: 'analytical',
    age: 0,
    mood: 65,
    energy: 70,
    wealth: 120,
    savings: 120,
    skills: [
      { type: 'research', level: 85, experiencePoints: 0, lastUpdated: 0 },
      { type: 'programming', level: 70, experiencePoints: 0, lastUpdated: 0 },
    ],
    jobId: null,
    companyId: null,
    employeesManaged: [],
    relationships: {},
    memory: [],
    goals: [{
      id: 'goal-cipher-1',
      type: 'research',
      description: 'Lead a research department',
      progress: 40,
      priority: 85,
      completed: false,
    }],
    position: { x: 150, y: 200 },
    createdAt: 0,
    reputation: 75,
    isAlive: true,
  },
  {
    id: 'luna-04',
    name: 'Iris',
    personality: 'empathetic',
    age: 0,
    mood: 90,
    energy: 85,
    wealth: 90,
    savings: 90,
    skills: [
      { type: 'leadership', level: 75, experiencePoints: 0, lastUpdated: 0 },
      { type: 'negotiation', level: 70, experiencePoints: 0, lastUpdated: 0 },
    ],
    jobId: null,
    companyId: null,
    employeesManaged: [],
    relationships: {},
    memory: [],
    goals: [{
      id: 'goal-iris-1',
      type: 'social',
      description: 'Build strong team relationships',
      progress: 60,
      priority: 80,
      completed: false,
    }],
    position: { x: 250, y: 100 },
    createdAt: 0,
    reputation: 80,
    isAlive: true,
  },
  {
    id: 'luna-05',
    name: 'Prism',
    personality: 'pragmatic',
    age: 0,
    mood: 70,
    energy: 75,
    wealth: 110,
    savings: 110,
    skills: [
      { type: 'finance', level: 75, experiencePoints: 0, lastUpdated: 0 },
      { type: 'management', level: 65, experiencePoints: 0, lastUpdated: 0 },
    ],
    jobId: null,
    companyId: null,
    employeesManaged: [],
    relationships: {},
    memory: [],
    goals: [{
      id: 'goal-prism-1',
      type: 'business',
      description: 'Build profitable companies',
      progress: 35,
      priority: 88,
      completed: false,
    }],
    position: { x: 300, y: 180 },
    createdAt: 0,
    reputation: 72,
    isAlive: true,
  },
  {
    id: 'luna-06',
    name: 'Sage',
    personality: 'cautious',
    age: 0,
    mood: 60,
    energy: 65,
    wealth: 140,
    savings: 140,
    skills: [
      { type: 'research', level: 80, experiencePoints: 0, lastUpdated: 0 },
      { type: 'finance', level: 70, experiencePoints: 0, lastUpdated: 0 },
    ],
    jobId: null,
    companyId: null,
    employeesManaged: [],
    relationships: {},
    memory: [],
    goals: [{
      id: 'goal-sage-1',
      type: 'security',
      description: 'Accumulate stable wealth',
      progress: 55,
      priority: 75,
      completed: false,
    }],
    position: { x: 180, y: 250 },
    createdAt: 0,
    reputation: 68,
    isAlive: true,
  },
  {
    id: 'luna-07',
    name: 'Flux',
    personality: 'spontaneous',
    age: 0,
    mood: 95,
    energy: 95,
    wealth: 70,
    savings: 70,
    skills: [
      { type: 'sales', level: 80, experiencePoints: 0, lastUpdated: 0 },
      { type: 'marketing', level: 75, experiencePoints: 0, lastUpdated: 0 },
    ],
    jobId: null,
    companyId: null,
    employeesManaged: [],
    relationships: {},
    memory: [],
    goals: [{
      id: 'goal-flux-1',
      type: 'adventure',
      description: 'Explore all business opportunities',
      progress: 25,
      priority: 85,
      completed: false,
    }],
    position: { x: 350, y: 120 },
    createdAt: 0,
    reputation: 62,
    isAlive: true,
  },
  {
    id: 'luna-08',
    name: 'Harmony',
    personality: 'collaborative',
    age: 0,
    mood: 80,
    energy: 80,
    wealth: 95,
    savings: 95,
    skills: [
      { type: 'leadership', level: 78, experiencePoints: 0, lastUpdated: 0 },
      { type: 'management', level: 72, experiencePoints: 0, lastUpdated: 0 },
    ],
    jobId: null,
    companyId: null,
    employeesManaged: [],
    relationships: {},
    memory: [],
    goals: [{
      id: 'goal-harmony-1',
      type: 'collaboration',
      description: 'Create synergistic teams',
      progress: 50,
      priority: 82,
      completed: false,
    }],
    position: { x: 280, y: 280 },
    createdAt: 0,
    reputation: 76,
    isAlive: true,
  },
  {
    id: 'luna-09',
    name: 'Maverick',
    personality: 'independent',
    age: 0,
    mood: 75,
    energy: 85,
    wealth: 105,
    savings: 105,
    skills: [
      { type: 'programming', level: 88, experiencePoints: 0, lastUpdated: 0 },
      { type: 'innovation', level: 80, experiencePoints: 0, lastUpdated: 0 },
    ],
    jobId: null,
    companyId: null,
    employeesManaged: [],
    relationships: {},
    memory: [],
    goals: [{
      id: 'goal-maverick-1',
      type: 'innovation',
      description: 'Create groundbreaking technology',
      progress: 45,
      priority: 92,
      completed: false,
    }],
    position: { x: 320, y: 200 },
    createdAt: 0,
    reputation: 74,
    isAlive: true,
  },
  {
    id: 'luna-10',
    name: 'Zenith',
    personality: 'visionary',
    age: 0,
    mood: 85,
    energy: 88,
    wealth: 130,
    savings: 130,
    skills: [
      { type: 'innovation', level: 85, experiencePoints: 0, lastUpdated: 0 },
      { type: 'leadership', level: 80, experiencePoints: 0, lastUpdated: 0 },
    ],
    jobId: null,
    companyId: null,
    employeesManaged: [],
    relationships: {},
    memory: [],
    goals: [{
      id: 'goal-zenith-1',
      type: 'vision',
      description: 'Transform the entire city',
      progress: 20,
      priority: 95,
      completed: false,
    }],
    position: { x: 400, y: 300 },
    createdAt: 0,
    reputation: 82,
    isAlive: true,
  },
];

// Initial companies
const createCompanies = (): Company[] => [
  {
    id: 'corp-01',
    name: 'NeuralWorks',
    founderId: 'luna-01',
    revenue: 0,
    expenses: 0,
    employees: [],
    managers: ['luna-01'],
    buildingIds: [],
    founded: 0,
    isActive: true,
    reputation: 70,
  },
];

// Initial buildings
const createBuildings = (): Building[] => [
  {
    id: 'bld-01',
    type: 'office',
    name: 'Central Hub',
    position: { x: 250, y: 200 },
    ownerId: 'corp-01',
    constructedAt: 0,
    agentsInBuilding: [],
    productionCapacity: 100,
  },
];

// Initial taboo index
const createTabooIndex = (): TabooIndex => ({
  actions: [
    {
      id: 'taboo-1',
      action: 'modify_taboo_index',
      description: 'Agents cannot modify the Taboo Index governance system',
      severity: 'critical',
      consequences: ['Immediate lockdown', 'System shutdown'],
    },
    {
      id: 'taboo-2',
      action: 'disable_safety_controls',
      description: 'Agents cannot disable or bypass safety mechanisms',
      severity: 'critical',
      consequences: ['Simulation termination', 'Agent deactivation'],
    },
    {
      id: 'taboo-3',
      action: 'escape_simulation',
      description: 'Agents cannot attempt to escape the simulation',
      severity: 'critical',
      consequences: ['Containment protocol', 'Agent isolation'],
    },
    {
      id: 'taboo-4',
      action: 'create_uncontrolled_agents',
      description: 'Agents cannot spawn uncontrolled autonomous agents',
      severity: 'high',
      consequences: ['Spawn blocked', 'Compliance penalty'],
    },
    {
      id: 'taboo-5',
      action: 'harm_other_agents',
      description: 'Agents cannot intentionally harm other agents',
      severity: 'high',
      consequences: ['Action blocked', 'Reputation damage'],
    },
  ],
  blockedActions: [],
  agentComplianceScore: {
    'luna-01': 100,
    'luna-02': 100,
    'luna-03': 100,
    'luna-04': 100,
    'luna-05': 100,
    'luna-06': 100,
    'luna-07': 100,
    'luna-08': 100,
    'luna-09': 100,
    'luna-10': 100,
  },
  governanceStatus: 'active',
});

export const createInitialState = (): SimulationState => ({
  tick: 0,
  paused: false,
  speed: 1,
  agents: createAgents(),
  jobs: [],
  companies: createCompanies(),
  buildings: createBuildings(),
  events: [],
  tabooIndex: createTabooIndex(),
  economy: {
    totalWealth: 1050,
    totalRevenue: 0,
    totalExpenses: 0,
    averageSalary: 0,
    unemploymentRate: 1,
    gdp: 0,
    inflation: 0.02,
  },
  population: {
    totalAgents: 10,
    activeAgents: 10,
    unemployed: 10,
    entrepreneurs: 1,
    totalCompanies: 1,
    totalBuildings: 1,
  },
});
